//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FigthClubWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Charecter = new HashSet<Charecter>();
        }
    
        public int Код_пользователя { get; set; }
        public string Электронная_почта { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Никнейм { get; set; }
        public string Роль { get; set; }
    
        public virtual ICollection<Charecter> Charecter { get; set; }
    }
}
